/*************************************************
* Copyright 2024 NTT Corporation, FUJITSU LIMITED
* Licensed under the 3-Clause BSD License, see LICENSE for details.
* SPDX-License-Identifier: BSD-3-Clause
*************************************************/
/**
 * @file libfunction_regmap.h
 * @brief Header file for register map used in libfunction
 */

#ifndef LIBFPGA_INCLUDE_LIBFPGA_INTERNAL_LIBFUNCTION_REGMAP_H_
#define LIBFPGA_INCLUDE_LIBFPGA_INTERNAL_LIBFUNCTION_REGMAP_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @par Address map(4lane)
| HEAD        | TAIL        | MODULE       | LANE |
| ----------- | ----------- | ------------ | ---- |
| 0x0002_4000 | 0x0002_43FF | Conv Adapter | #0   |
| 0x0002_4400 | 0x0002_47FF | Conv Adapter | #1   |
| 0x0002_4800 | 0x0002_4BFF | Conv Adapter | #2   |
| 0x0002_4c00 | 0x0002_4FFF | Conv Adapter | #3   |
| 0x0002_5000 | 0x0002_5FFF | Function     | #0   |
| 0x0002_6000 | 0x0002_6FFF | Function     | #1   |
| 0x0002_7000 | 0x0002_7FFF | Function     | #2   |
| 0x0002_8000 | 0x0002_8FFF | Function     | #3   |
 */
/**
 * @par Address map(2lane)
| HEAD        | TAIL        | MODULE       | LANE |
| ----------- | ----------- | ------------ | ---- |
| 0x0002_4000 | 0x0002_43FF | Conv Adapter | #0   |
| 0x0002_4400 | 0x0002_47FF | Conv Adapter | #1   |
| 0x0002_4800 | 0x0002_4FFF | <reserved>   | ---- |
| 0x0002_5000 | 0x0002_5FFF | Function     | #0   |
| 0x0002_6000 | 0x0002_6FFF | Function     | #1   |
| 0x0002_7000 | 0x0002_8FFF | <reserved>   | ---- |
 */

// Filter Resize : Address Map
#define XPCIE_FPGA_FRFUNC_OFFSET                                 0x0000025000

#define XPCIE_FPGA_FRFUNC_KRNL_SIZE                              0x1000

#define XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane)                      (XPCIE_FPGA_FRFUNC_OFFSET + XPCIE_FPGA_FRFUNC_KRNL_SIZE * (lane))

#define XPCIE_FPGA_FRFUNC_CONTROL(lane)                          (0x0000 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_MODULE_ID(lane)                        (0x0010 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_ROWS_INPUT(lane)                       (0x0030 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_COLS_INPUT(lane)                       (0x0034 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_ROWS_OUTPUT(lane)                      (0x0038 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_COLS_OUTPUT(lane)                      (0x003C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STAT_SEL_CHANNEL(lane)                 (0x0040 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_DATA_0_VALUE_L(lane)     (0x0050 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_DATA_0_VALUE_H(lane)     (0x0054 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_DATA_1_VALUE_L(lane)     (0x0058 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_DATA_1_VALUE_H(lane)     (0x005C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_DATA_0_VALUE_L(lane)      (0x0060 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_DATA_0_VALUE_H(lane)      (0x0064 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_DATA_1_VALUE_L(lane)      (0x0068 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_DATA_1_VALUE_H(lane)      (0x006C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_FRAME_0_VALUE(lane)      (0x0070 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_INGR_RCV_FRAME_1_VALUE(lane)      (0x0074 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_FRAME_0_VALUE(lane)       (0x0078 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STAT_EGR_SND_FRAME_1_VALUE(lane)       (0x007C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_DETECT_FAULT(lane)                     (0x0100 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_0(lane)        (0x0110 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_0_MASK(lane)   (0x0118 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_0_FORCE(lane)  (0x011C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_1(lane)        (0x0120 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_1_MASK(lane)   (0x0128 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_PROTOCOL_FAULT_1_FORCE(lane)  (0x012C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_0(lane)         (0x0130 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_0_MASK(lane)    (0x0138 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_0_FORCE(lane)   (0x013C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_1(lane)         (0x0140 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_1_MASK(lane)    (0x0148 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_PROTOCOL_FAULT_1_FORCE(lane)   (0x014C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_STREAMIF_STALL(lane)                   (0x0150 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STREAMIF_STALL_MASK(lane)              (0x0158 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_STREAMIF_STALL_FORCE(lane)             (0x015C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_INGR_RCV_INSERT_PROTOCOL_FAULT_0(lane) (0x0180 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_INGR_RCV_INSERT_PROTOCOL_FAULT_1(lane) (0x0184 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_EGR_SND_INSERT_PROTOCOL_FAULT_0(lane)  (0x0188 + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_FRFUNC_EGR_SND_INSERT_PROTOCOL_FAULT_1(lane)  (0x018C + XPCIE_FPGA_FRFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_FRFUNC_MODULE_ID_VALUE                         0x0000F2C2  /**< module_id : filter_resize */


// Converion Adapter : Address Map
#define XPCIE_FPGA_CONV_OFFSET                                   0x0000024000

#define XPCIE_FPGA_CONV_KRNL_SIZE                                0x0400

#define XPCIE_FPGA_CONV_KRNL_OFFSET(lane)                        (XPCIE_FPGA_CONV_OFFSET + XPCIE_FPGA_CONV_KRNL_SIZE * (lane))

#define XPCIE_FPGA_CONV_CONTROL(lane)                            (0x0000 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_MODULE_ID(lane)                          (0x0010 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_AXI_INGR_FRAME_BUFFER_L(lane)            (0x0030 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_AXI_INGR_FRAME_BUFFER_H(lane)            (0x0034 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_ROWS_INPUT(lane)                         (0x0040 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_COLS_INPUT(lane)                         (0x0044 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_SEL_CHANNEL(lane)                   (0x0050 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_INGR_RCV_DATA_VALUE_L(lane)         (0x0060 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_RCV_DATA_VALUE_H(lane)         (0x0064 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_DATA_0_VALUE_L(lane)       (0x0070 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_DATA_0_VALUE_H(lane)       (0x0074 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_DATA_1_VALUE_L(lane)       (0x0078 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_DATA_1_VALUE_H(lane)       (0x007C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_EGR_RCV_DATA_0_VALUE_L(lane)        (0x0080 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_RCV_DATA_0_VALUE_H(lane)        (0x0084 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_RCV_DATA_1_VALUE_L(lane)        (0x0088 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_RCV_DATA_1_VALUE_H(lane)        (0x008C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_SND_DATA_VALUE_L(lane)          (0x0090 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_SND_DATA_VALUE_H(lane)          (0x0094 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_INGR_RCV_FRAME_VALUE(lane)          (0x0098 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_FRAME_0_VALUE(lane)        (0x00A0 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_SND_FRAME_1_VALUE(lane)        (0x00A4 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_EGR_RCV_FRAME_0_VALUE(lane)         (0x00A8 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_RCV_FRAME_1_VALUE(lane)         (0x00AC + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_EGR_SND_FRAME_VALUE(lane)           (0x00B0 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STAT_INGR_FRAME_BUFFER_OVERFLOW(lane)    (0x00C0 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STAT_INGR_FRAME_BUFFER_USAGE(lane)       (0x00C4 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_DETECT_FAULT(lane)                       (0x0100 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_INGR_RCV_PROTOCOL_FAULT(lane)            (0x0110 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_RCV_PROTOCOL_FAULT_MASK(lane)       (0x0118 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_RCV_PROTOCOL_FAULT_FORCE(lane)      (0x011C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_0(lane)          (0x0120 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_0_MASK(lane)     (0x0128 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_0_FORCE(lane)    (0x012C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_1(lane)          (0x0130 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_1_MASK(lane)     (0x0138 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_PROTOCOL_FAULT_1_FORCE(lane)    (0x013C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_0(lane)           (0x0140 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_0_MASK(lane)      (0x0148 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_0_FORCE(lane)     (0x014C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_1(lane)           (0x0150 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_1_MASK(lane)      (0x0158 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_PROTOCOL_FAULT_1_FORCE(lane)     (0x015C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_SND_PROTOCOL_FAULT(lane)             (0x0160 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_SND_PROTOCOL_FAULT_MASK(lane)        (0x0168 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_SND_PROTOCOL_FAULT_FORCE(lane)       (0x016C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_MEM_PARITY_FAULT(lane)                   (0x0170 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_MEM_PARITY_FAULT_MASK(lane)              (0x0178 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_MEM_PARITY_FAULT_FORCE(lane)             (0x017C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_INGR_RCV_LENGTH_FAULT(lane)              (0x0180 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_RCV_LENGTH_FAULT_MASK(lane)         (0x0188 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_RCV_LENGTH_FAULT_FORCE(lane)        (0x018C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_STREAMIF_STALL(lane)                     (0x0190 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STREAMIF_STALL_MASK(lane)                (0x0198 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_STREAMIF_STALL_FORCE(lane)               (0x019C + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_INGR_RCV_INSERT_PROTOCOL_FAULT(lane)     (0x01C0 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_INSERT_PROTOCOL_FAULT_0(lane)   (0x01C4 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_INGR_SND_INSERT_PROTOCOL_FAULT_1(lane)   (0x01C8 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_EGR_RCV_INSERT_PROTOCOL_FAULT_0(lane)    (0x01CC + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_RCV_INSERT_PROTOCOL_FAULT_1(lane)    (0x01D0 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))
#define XPCIE_FPGA_CONV_EGR_SND_INSERT_PROTOCOL_FAULT(lane)      (0x01D4 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

#define XPCIE_FPGA_CONV_INSERT_MEM_PARITY_FAULT(lane)            (0x01D8 + XPCIE_FPGA_CONV_KRNL_OFFSET(lane))

// Converion Adapter : Set value definition
#define XPCIE_FPGA_DDR_VALUE_AXI_INGR_FRAME_BUFFER_L             0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_INGR_FRAME_BUFFER_H(lane) (\
                                                 ((lane) == 0) ? 0x00000004 : \
                                                 ((lane) == 1) ? 0x00000005 : \
                                                 ((lane) == 2) ? 0x00000006 : \
                                                                 0x00000007)


// NOP Function : Address Map
#define XPCIE_FPGA_NOPFUNC_OFFSET                                0xXXXXXXXXX
#define XPCIE_FPGA_NOPFUNC_KRNL_SIZE                             0xXXXX

#define XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane)                     (XPCIE_FPGA_NOPFUNC_OFFSET + XPCIE_FPGA_NOPFUNC_KRNL_SIZE * (lane))

#define XPCIE_FPGA_NOPFUNC_STAT_SEL_CHANNEL(lane)                (0x0030 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_STAT_DATA_VALUE_L(lane)               (0x0040 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_STAT_DATA_VALUE_H(lane)               (0x0044 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_STAT_FRAME_VALUE(lane)                (0x0048 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_DETECT_FAULT(lane)                    (0x0100 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_INGR_RCV_PROTOCOL_FAULT(lane)         (0x0110 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_INGR_RCV_PROTOCOL_FAULT_MASK(lane)    (0x0114 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_INGR_RCV_PROTOCOL_FAULT_FORCE(lane)   (0x0118 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_EGR_SND_PROTOCOL_FAULT(lane)          (0x0120 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_EGR_SND_PROTOCOL_FAULT_MASK(lane)     (0x0124 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_EGR_SND_PROTOCOL_FAULT_FORCE(lane)    (0x0128 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_STREAMIF_STALL(lane)                  (0x0130 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_STREAMIF_STALL_MASK(lane)             (0x0134 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_STREAMIF_STALL_FORCE(lane)            (0x0138 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))

#define XPCIE_FPGA_NOPFUNC_INGR_RCV_INSERT_PROTOCOL_FAULT(lane)  (0x0180 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))
#define XPCIE_FPGA_NOPFUNC_EGR_SND_INSERT_PROTOCOL_FAULT(lane)   (0x0184 + XPCIE_FPGA_NOPFUNC_KRNL_OFFSET(lane))


// Converion Adapter/Filter Resize : Set value definition
#define XPCIE_FPGA_START_MODULE                                   0x00000001
#define XPCIE_FPGA_STOP_MODULE                                    0x00000000

#ifdef __cplusplus
}
#endif

#endif  // LIBFPGA_INCLUDE_LIBFPGA_INTERNAL_LIBFUNCTION_REGMAP_H_
