/*************************************************
* Copyright 2024 NTT Corporation, FUJITSU LIMITED
* Licensed under the GPL-2.0  License, see LICENSE for details.
* SPDX-License-Identifier: GPL-2.0-or-later
*************************************************/
/**
 * @file xpcie_regs_chain.h
 * @brief Header file for register map for chain module
 */

#ifndef __CHAIN_XPCIE_REGS_CHAIN_H__
#define __CHAIN_XPCIE_REGS_CHAIN_H__


// Chain_Control Register Map : 0x0000_1000-0x0000_4FFF
#define XPCIE_FPGA_CHAIN_OFFSET                                   0x0000001000 /**< Base address for Chain */
#define XPCIE_FPGA_CHAIN_SIZE                                     0x1000       /**< Size of Chain per a lane */

#define XPCIE_FPGA_CHAIN_CONTROL                                  0x0000
#define XPCIE_FPGA_CHAIN_MODULE_ID                                0x0010

#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_BASE_L                 0x0100
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_BASE_H                 0x0104

#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_RX_OFFSET_L            0x0110
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_RX_OFFSET_H            0x0114
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_RX_STRIDE              0x0118
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_RX_SIZE                0x011C

#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_TX_OFFSET_L            0x0120
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_TX_OFFSET_H            0x0124
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_TX_STRIDE              0x0128
#define XPCIE_FPGA_CHAIN_AXI_EXTIF0_BUFFER_TX_SIZE                0x012C

#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_BASE_L                 0x0140
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_BASE_H                 0x0144

#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_RX_OFFSET_L            0x0150
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_RX_OFFSET_H            0x0154
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_RX_STRIDE              0x0158
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_RX_SIZE                0x015C

#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_TX_OFFSET_L            0x0160
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_TX_OFFSET_H            0x0164
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_TX_STRIDE              0x0168
#define XPCIE_FPGA_CHAIN_AXI_EXTIF1_BUFFER_TX_SIZE                0x016C

#define XPCIE_FPGA_CHAIN_INGR_FORWARD_UPDATE_REQ                  0x0200
#define XPCIE_FPGA_CHAIN_INGR_FORWARD_UPDATE_RESP                 0x0204
#define XPCIE_FPGA_CHAIN_INGR_FORWARD_SESSION                     0x0208
#define XPCIE_FPGA_CHAIN_INGR_FORWARD_CHANNEL                     0x020C

#define XPCIE_FPGA_CHAIN_EGR_FORWARD_UPDATE_REQ                   0x0220
#define XPCIE_FPGA_CHAIN_EGR_FORWARD_UPDATE_RESP                  0x0224
#define XPCIE_FPGA_CHAIN_EGR_FORWARD_CHANNEL                      0x0228
#define XPCIE_FPGA_CHAIN_EGR_FORWARD_SESSION                      0x022C

#define XPCIE_FPGA_CHAIN_STAT_SEL_SESSION                         0x0300
#define XPCIE_FPGA_CHAIN_STAT_SEL_CHANNEL                         0x0308

#define XPCIE_FPGA_CHAIN_INGR_LATENCY_0_VALUE                     0x0320
#define XPCIE_FPGA_CHAIN_INGR_LATENCY_1_VALUE                     0x0324
#define XPCIE_FPGA_CHAIN_EGR_LATENCY_0_VALUE                      0x0328
#define XPCIE_FPGA_CHAIN_EGR_LATENCY_1_VALUE                      0x032C
#define XPCIE_FPGA_CHAIN_FUNC_LATENCY_VALUE                       0x0330

#define XPCIE_FPGA_CHAIN_STAT_INGR_RCV_DATA_0_VALUE_L             0x0340
#define XPCIE_FPGA_CHAIN_STAT_INGR_RCV_DATA_0_VALUE_H             0x0344
#define XPCIE_FPGA_CHAIN_STAT_INGR_RCV_DATA_1_VALUE_L             0x0348
#define XPCIE_FPGA_CHAIN_STAT_INGR_RCV_DATA_1_VALUE_H             0x034C
#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_DATA_0_VALUE_L             0x0350
#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_DATA_0_VALUE_H             0x0354
#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_DATA_1_VALUE_L             0x0358
#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_DATA_1_VALUE_H             0x035C

#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_DATA_0_VALUE_L              0x0360
#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_DATA_0_VALUE_H              0x0364
#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_DATA_1_VALUE_L              0x0368
#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_DATA_1_VALUE_H              0x036C
#define XPCIE_FPGA_CHAIN_STAT_EGR_SND_DATA_0_VALUE_L              0x0370
#define XPCIE_FPGA_CHAIN_STAT_EGR_SND_DATA_0_VALUE_H              0x0374
#define XPCIE_FPGA_CHAIN_STAT_EGR_SND_DATA_1_VALUE_L              0x0378
#define XPCIE_FPGA_CHAIN_STAT_EGR_SND_DATA_1_VALUE_H              0x037C

#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_FRAME_0_VALUE              0x0380
#define XPCIE_FPGA_CHAIN_STAT_INGR_SND_FRAME_1_VALUE              0x0384
#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_FRAME_0_VALUE               0x0388
#define XPCIE_FPGA_CHAIN_STAT_EGR_RCV_FRAME_1_VALUE               0x038C

#define XPCIE_FPGA_CHAIN_STAT_INGR_DISCARD_DATA_0_VALUE_L         0x03A0
#define XPCIE_FPGA_CHAIN_STAT_INGR_DISCARD_DATA_0_VALUE_H         0x03A4
#define XPCIE_FPGA_CHAIN_STAT_INGR_DISCARD_DATA_1_VALUE_L         0x03A8
#define XPCIE_FPGA_CHAIN_STAT_INGR_DISCARD_DATA_1_VALUE_H         0x03AC

#define XPCIE_FPGA_CHAIN_STAT_EGR_DISCARD_DATA_0_VALUE_L          0x03B0
#define XPCIE_FPGA_CHAIN_STAT_EGR_DISCARD_DATA_0_VALUE_H          0x03B4
#define XPCIE_FPGA_CHAIN_STAT_EGR_DISCARD_DATA_1_VALUE_L          0x03B8
#define XPCIE_FPGA_CHAIN_STAT_EGR_DISCARD_DATA_1_VALUE_H          0x03BC

#define XPCIE_FPGA_CHAIN_STAT_HEADER_BUFF_STORED                  0x0400
#define XPCIE_FPGA_CHAIN_STAT_HEADER_BUFF_BP                      0x0404

#define XPCIE_FPGA_CHAIN_STAT_EGR_BUSY                            0x040C

#define XPCIE_FPGA_CHAIN_EXTIF0_SESSION_STATUS                    0x0410
#define XPCIE_FPGA_CHAIN_EXTIF1_SESSION_STATUS                    0x0414

#define XPCIE_FPGA_CHAIN_DETECT_FAULT                             0x0500

#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_0_VALUE            0x0510
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_0_MASK             0x0518
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_0_FORCE            0x051C
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_1_VALUE            0x0520
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_1_MASK             0x0528
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_1_FORCE            0x052C

#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_0_VALUE            0x0530
#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_0_MASK             0x0538
#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_0_FORCE            0x053C
#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_1_VALUE            0x0540
#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_1_MASK             0x0548
#define XPCIE_FPGA_CHAIN_INGR_SND_DETECT_FAULT_1_FORCE            0x054C

#define XPCIE_FPGA_CHAIN_EGR_RCV_DETECT_FAULT_VALUE               0x0550
#define XPCIE_FPGA_CHAIN_EGR_RCV_DETECT_FAULT_MASK                0x0558
#define XPCIE_FPGA_CHAIN_EGR_RCV_DETECT_FAULT_FORCE               0x055C

#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_0_VALUE             0x0560
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_0_MASK              0x0568
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_0_FORCE             0x056C
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_1_VALUE             0x0570
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_1_MASK              0x0578
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_1_FORCE             0x057C

#define XPCIE_FPGA_CHAIN_INGR_SND_PROTOCOL_FAULT                  0x0580
#define XPCIE_FPGA_CHAIN_INGR_SND_PROTOCOL_FAULT_MASK             0x0588
#define XPCIE_FPGA_CHAIN_INGR_SND_PROTOCOL_FAULT_FORCE            0x058C
#define XPCIE_FPGA_CHAIN_EGR_RCV_PROTOCOL_FAULT                   0x0590
#define XPCIE_FPGA_CHAIN_EGR_RCV_PROTOCOL_FAULT_MASK              0x0598
#define XPCIE_FPGA_CHAIN_EGR_RCV_PROTOCOL_FAULT_FORCE             0x059C

#define XPCIE_FPGA_CHAIN_EXTIF0_EVENT_FAULT                       0x05A0
#define XPCIE_FPGA_CHAIN_EXTIF0_EVENT_FAULT_MASK                  0x05A8
#define XPCIE_FPGA_CHAIN_EXTIF0_EVENT_FAULT_FORCE                 0x05AC
#define XPCIE_FPGA_CHAIN_EXTIF1_EVENT_FAULT                       0x05B0
#define XPCIE_FPGA_CHAIN_EXTIF1_EVENT_FAULT_MASK                  0x05B8
#define XPCIE_FPGA_CHAIN_EXTIF1_EVENT_FAULT_FORCE                 0x05BC

#define XPCIE_FPGA_CHAIN_STREAMIF_STALL                           0x05C0
#define XPCIE_FPGA_CHAIN_STREAMIF_STALL_MASK                      0x05C8
#define XPCIE_FPGA_CHAIN_STREAMIF_STALL_FORCE                     0x05CC

#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_0_INS              0x0600
#define XPCIE_FPGA_CHAIN_INGR_RCV_DETECT_FAULT_1_INS              0x0604
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_0_INS               0x0608
#define XPCIE_FPGA_CHAIN_EGR_SND_DETECT_FAULT_1_INS               0x060C
#define XPCIE_FPGA_CHAIN_INGR_SND_PROTOCOL_FAULT_INS              0x0610
#define XPCIE_FPGA_CHAIN_EGR_RCV_PROTOCOL_FAULT_INS               0x0614
#define XPCIE_FPGA_CHAIN_EXTIF0_CMDFAULT_INS                      0x0618
#define XPCIE_FPGA_CHAIN_EXTIF1_CMDFAULT_INS                      0x061C

// Setting value as DDR buffer
#ifndef EXTIFINV
/* EXTIF1 = NW, EXTIF0 = LLDMA */
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_BASE_L             0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_BASE_H(lane)       0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_OFFSET_L        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_STRIDE          0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_SIZE            0x0000000A
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_OFFSET_L        0x02000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_STRIDE          0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_SIZE            0x0000000A

#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_BASE_L             0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_BASE_H(lane) (\
                                                  ((lane) == 0) ? 0x00000008 : \
                                                  ((lane) == 1) ? 0x00000009 : \
                                                  ((lane) == 2) ? 0x0000000A : \
                                                                  0x0000000B)
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_OFFSET_L        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_STRIDE          0x00200000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_SIZE            0x0000000A
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_OFFSET_L        0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_STRIDE          0x00200000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_SIZE            0x0000000A
#else
/* EXTIF0 = NW, EXTIF1 = LLDMA */
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_BASE_L             0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_BASE_H(lane) (\
                                                  ((lane) == 0) ? 0x00000008 : \
                                                  ((lane) == 1) ? 0x00000009 : \
                                                  ((lane) == 2) ? 0x0000000A : \
                                                                  0x0000000B)
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_OFFSET_L        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_STRIDE          0x00200000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_RX_SIZE            0x0000000A
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_OFFSET_L        0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_STRIDE          0x00200000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF0_BUFFER_TX_SIZE            0x0000000A
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_BASE_L             0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_BASE_H(lane)       0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_OFFSET_L        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_STRIDE          0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_RX_SIZE            0x0000000A
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_OFFSET_L        0x02000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_OFFSET_H        0x00000000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_STRIDE          0x00100000
#define XPCIE_FPGA_DDR_VALUE_AXI_EXTIF1_BUFFER_TX_SIZE            0x0000000A
#endif

#define XPCIE_FPGA_START_MODULE                                   0x00000001
#define XPCIE_FPGA_STOP_MODULE                                    0x00000000

#define XPCIE_FPGA_CHAIN_MODULE_ID_VALUE                          0x0000F0C0   /**< module_id : Chain */

#endif  /* __CHAIN_XPCIE_REGS_CHAIN_H__ */
