/*************************************************
* Copyright 2024 NTT Corporation, FUJITSU LIMITED
* Licensed under the GPL-2.0  License, see LICENSE for details.
* SPDX-License-Identifier: GPL-2.0-or-later
*************************************************/
/**
 * @file xpcie_regs_direct.h
 * @brief Header file for register map for direct module
 */

#ifndef __DIRECT_XPCIE_REGS_DIRECT_H__
#define __DIRECT_XPCIE_REGS_DIRECT_H__


// Direct transfer Register Map
#define XPCIE_FPGA_DIRECT_OFFSET                        0x0000005000 /**< Base address for Direct */
#define XPCIE_FPGA_DIRECT_SIZE                          0x1000       /**< Size of Direct per a lane */

#define XPCIE_FPGA_DIRECT_CONTROL                       0x0000
#define XPCIE_FPGA_DIRECT_MODULE_ID                     0x0010

#define XPCIE_FPGA_DIRECT_STAT_SEL_CHANNEL              0x0040

#define XPCIE_FPGA_DIRECT_STAT_INGR_RCV_DATA_VALUE_L    0x0050
#define XPCIE_FPGA_DIRECT_STAT_INGR_RCV_DATA_VALUE_H    0x0054
#define XPCIE_FPGA_DIRECT_STAT_INGR_SND_DATA_VALUE_L    0x0058
#define XPCIE_FPGA_DIRECT_STAT_INGR_SND_DATA_VALUE_H    0x005C
#define XPCIE_FPGA_DIRECT_STAT_EGR_RCV_DATA_VALUE_L     0x0060
#define XPCIE_FPGA_DIRECT_STAT_EGR_RCV_DATA_VALUE_H     0x0064
#define XPCIE_FPGA_DIRECT_STAT_EGR_SND_DATA_VALUE_L     0x0068
#define XPCIE_FPGA_DIRECT_STAT_EGR_SND_DATA_VALUE_H     0x006C

#define XPCIE_FPGA_DIRECT_STAT_INGR_RCV_FRAME_VALUE     0x0070
#define XPCIE_FPGA_DIRECT_STAT_INGR_SND_FRAME_VALUE     0x0074
#define XPCIE_FPGA_DIRECT_STAT_EGR_RCV_FRAME_VALUE      0x0078
#define XPCIE_FPGA_DIRECT_STAT_EGR_SND_FRAME_VALUE      0x007C

#define XPCIE_FPGA_DIRECT_DETECT_FAULT                  0x0100

#define XPCIE_FPGA_DIRECT_INGR_RCV_PROTOCOL_FAULT       0x0110
#define XPCIE_FPGA_DIRECT_INGR_RCV_PROTOCOL_FAULT_MASK  0x0118
#define XPCIE_FPGA_DIRECT_INGR_RCV_PROTOCOL_FAULT_FORCE 0x011C
#define XPCIE_FPGA_DIRECT_INGR_SND_PROTOCOL_FAULT       0x0120
#define XPCIE_FPGA_DIRECT_INGR_SND_PROTOCOL_FAULT_MASK  0x0128
#define XPCIE_FPGA_DIRECT_INGR_SND_PROTOCOL_FAULT_FORCE 0x012C

#define XPCIE_FPGA_DIRECT_EGR_RCV_PROTOCOL_FAULT        0x0130
#define XPCIE_FPGA_DIRECT_EGR_RCV_PROTOCOL_FAULT_MASK   0x0138
#define XPCIE_FPGA_DIRECT_EGR_RCV_PROTOCOL_FAULT_FORCE  0x013C
#define XPCIE_FPGA_DIRECT_EGR_SND_PROTOCOL_FAULT        0x0140
#define XPCIE_FPGA_DIRECT_EGR_SND_PROTOCOL_FAULT_MASK   0x0148
#define XPCIE_FPGA_DIRECT_EGR_SND_PROTOCOL_FAULT_FORCE  0x014C

#define XPCIE_FPGA_DIRECT_STREAMIF_STALL                0x0150
#define XPCIE_FPGA_DIRECT_STREAMIF_STALL_MASK           0x0158
#define XPCIE_FPGA_DIRECT_STREAMIF_STALL_FORCE          0x015C

#define XPCIE_FPGA_DIRECT_INGR_RCV_PROTOCOL_FAULT_INS   0x0180
#define XPCIE_FPGA_DIRECT_INGR_SND_PROTOCOL_FAULT_INS   0x0184
#define XPCIE_FPGA_DIRECT_EGR_RCV_PROTOCOL_FAULT_INS    0x0188
#define XPCIE_FPGA_DIRECT_EGR_SND_PROTOCOL_FAULT_INS    0x018C

#define XPCIE_FPGA_START_MODULE                         0x00000001
#define XPCIE_FPGA_STOP_MODULE                          0x00000000

#define XPCIE_FPGA_DIRECT_MODULE_ID_VALUE               0x0000F3C0 /**< module_id : Direct_transfer */

#endif  /* __DIRECT_XPCIE_REGS_DIRECT_H__ */
