#=================================================
# Copyright 2025 NTT Corporation
# Licensed under the 3-Clause BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause
#=================================================

.PHONY: toe_config

all: toe_config

toe_config:
	@+make -C toe_config

clean:
	@make -C toe_config clean

